version: "2.1"

orbs:
    utility-orb: hamza-runner-ns/utility-orb@0.0.1
    pulling-orb: hamza-runner-ns/pulling-orb@0.0.1

jobs:
  orb_test:
    docker:
      - image: cimg/python:3.9.7
    steps:
      - checkout
      - pulling-orb/greet



workflows:
  build_and_test:
    jobs:
      - orb_test
