version: "2.1"
jobs:
  Build:
    machine: true
    resource_class: hamza-runner-ns/hamza-rc
    steps:
      - checkout
      - run: echo "Hello World"
workflows:
  BuildTestDeploy:
    jobs:
      - Build
