version: "2.1"
jobs:
  Build:
    machine: true
    resource_class: hamza-runner-ns/hamza-rc
    steps:
      - checkout
      - run: echo "Hi World"

  Build2:
    machine: true
    resource_class: hamza-runner-ns/hamza-rc
    steps:
      - run: |
            echo "Pulling image"
            u="$USER"
            echo "User name $u"
            docker pull python
            echo "Start container"
            docker run -it --user root python bash
            echo "checkout code "
            checkout
            ls
workflows:
  BuildTestDeploy:
    jobs:
      - Build
      - Build2
