version: "2.1"
jobs:
  Build:
    machine: true
    resource_class: hamza-runner-ns/hamza-rc
    steps:
      - checkout
      - run: echo "Hi World"

  Build2:
    machine: true
    resource_class: hamza-runner-ns/hamza-rc
    steps:
      - run: 
          name: Execute container commands
          command: |
#            echo "Pulling image"
#            u="$USER"
#            echo "User name $u"
#            docker pull python
#            echo "Start container"
#            docker run -d python echo "I'm inside the container!"
             checkout
             docker build -t hamza/container .
             docker run -p80:3000 hamza/container
             docker ps -a


workflows:
  BuildTestDeploy:
    jobs:
      - Build
      - Build2
