version: "2.1"

orbs:
    internal: hamza-runner-ns/internal-testing@0.0.1

jobs:
  orb_test:
    docker:
      - image: cimg/python:3.9.7
    steps:
      - checkout
      - internal/enter



workflows:
  build_and_test:
    jobs:
      - orb_test
