version: "2.1"
jobs:
  Build:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: echo "Hello World"
  Build2:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: echo "Hello World"
  Build3:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: echo "Hello World"
  Deploy:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: echo "Hello World"
  Deploy1:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: echo "Hello World"
workflows:
  Test:
    jobs:
      - Build
      - Build2
      - Build3
      - Deploy:
          requires:
            - Build2
            - Build3
      - Deploy1:
          requires:
            - Build
            - Build2
