version: "2.1"

orbs:
    pulling-orb: hamza-runner-ns/pulling-orb@0.0.1


jobs:
  orb_test:
    docker:
      - image: cimg/python:3.9.7
    steps:
      - checkout
      - pulling-orb/greet



workflows:
  build_and_test:
    jobs:
      - orb_test
