version: "2.1"

jobs:
  Build:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: echo "Hello World"
  Lint:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: echo "Hello World"
  Deploy:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: echo "Hello World"
  Test:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: echo "Hello World"
workflows:
  Build:
    jobs:
      - Build
      - Lint
      - Deploy:
          requires:
            - Test
      - Test:
          requires:
            - Build
            - Lint
