version: "2.1"

orbs:
    angular-orb-training: hamza-runner-ns/angular-orb-training@1.0.0


jobs:
  orb_test:
    docker:
      - image: cimg/python:3.9.7
    steps:
      - checkout
      - run: echo "Hello World"
      - run: pwd
      - run: ls -al
      - angular-orb-training/install-python:
          from-file: requirements.txt


  
workflows:
  build_and_test:
    jobs:
      - orb_test
